import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f8f8',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 10,
    backgroundColor: '#fff',
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  summaryBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  summaryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff0f2',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    gap: 4,
  },
  summaryText: {
    fontSize: 12,
    color: '#E8445A',
    fontWeight: '500',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginVertical: 8,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#ececec',
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    paddingVertical: 0,
  },
  filterWrapper: {
    height: 52,
    marginVertical: 4,
  },
  filterRow: {
    paddingHorizontal: 16,
    gap: 8,
    alignItems: 'center',
    height: '100%',
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
  },
  filterChipActive: {
    backgroundColor: '#E8445A',
    borderColor: '#E8445A',
  },
  filterText: {
    fontSize: 13,
    color: '#333',
    fontWeight: '500',
  },
  filterTextActive: {
    color: '#fff',
    fontWeight: 'bold',
  },
  countText: {
    fontSize: 14,
    color: '#555',
    paddingHorizontal: 16,
    marginBottom: 8,
    marginTop: 4,
  },
  countHighlight: {
    color: '#E8445A',
    fontWeight: 'bold',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 60,
    gap: 8,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 12,
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#888',
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingBottom: 20,
    gap: 16,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cardImage: {
    width: '100%',
    height: 200,
  },
  wishlistBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 6,
    elevation: 2,
  },
  femaleSafeBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: '#E8445A',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  femaleSafeBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },

  // ── Availability badge (top-right on card image) ──────────────────────────
  availBadge: {
    position: 'absolute',
    top: 12,
    right: 48,                // offset left of the wishlist button
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  availBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },

  cardInfo: {
    padding: 14,
  },
  nameRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  hotelName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1a1a1a',
    flex: 1,
    marginRight: 8,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8445A',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
  },
  ratingText: {
    fontSize: 12,
    color: '#fff',
    fontWeight: 'bold',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 3,
  },
  locationText: {
    fontSize: 12,
    color: '#777',
  },
  amenityChip: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  amenityText: {
    fontSize: 11,
    color: '#555',
  },

  // ── Dorm availability bar ─────────────────────────────────────────────────
  availBarWrapper: {
    marginBottom: 10,
  },
  availBarRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  availBarLabel: {
    fontSize: 11,
    color: '#888',
    fontWeight: '500',
  },
  availBarPct: {
    fontSize: 11,
    fontWeight: '700',
  },
  availBarTrack: {
    height: 5,
    borderRadius: 4,
    backgroundColor: '#f0f0f0',
    overflow: 'hidden',
  },
  availBarFill: {
    height: '100%',
    borderRadius: 4,
  },

  divider: {
    height: 1,
    backgroundColor: '#f0f0f0',
    marginBottom: 12,
  },
  bottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  priceSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  priceCol: {
    flex: 1,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginVertical: 2,
    flexWrap: 'nowrap',
  },
  priceLabel: {
    fontSize: 11,
    color: '#888',
  },
  priceMain: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  priceOriginal: {
    fontSize: 11,
    color: '#bbb',
    textDecorationLine: 'line-through',
  },
  discountText: {
    fontSize: 11,
    color: '#E8445A',
    fontWeight: '700',
  },
  priceDivider: {
    width: 1,
    height: 44,
    backgroundColor: '#e0e0e0',
    marginHorizontal: 10,
    alignSelf: 'center',
  },
  selectBtn: {
    backgroundColor: '#E8445A',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignSelf: 'center',
  },
  selectBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 13,
  },
});